"""Initial database schema for workout tracking.

upgrade() creates the tables described by the models. Creating this file alone
does not change the database; Alembic runs it only when asked to upgrade.

Revision ID: 3df330aa401f
Revises: 
Create Date: 2026-10-05 20:46:21.981885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df330aa401f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('primary_muscle_group', sa.String(length=60), nullable=False),
    sa.Column('equipment', sa.String(length=80), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_routines',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_exercises',
    sa.Column('routine_id', sa.String(length=100), nullable=False),
    sa.Column('exercise_id', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['workout_routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routine_id', 'exercise_id'),
    sa.UniqueConstraint('routine_id', 'position', name='uq_routine_exercise_position')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('routine_id', sa.String(length=100), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['workout_routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_user_performed', 'workout_sessions', ['user_id', 'performed_at'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_session_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_session_id', 'position', name='uq_workout_exercise_position')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.CheckConstraint('reps > 0', name='ck_workout_set_reps_positive'),
    sa.CheckConstraint('set_number > 0', name='ck_workout_set_number_positive'),
    sa.CheckConstraint('weight_kg >= 0', name='ck_workout_set_weight_nonnegative'),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_exercise_id', 'set_number', name='uq_workout_set_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('workout_exercises')
    op.drop_index('ix_workout_user_performed', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_table('routine_exercises')
    op.drop_table('workout_routines')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
